- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
    files: '(handler.py|reddit/.*)'

- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
  - id: isort
    language_version: python3.7
    files: '(handler.py|reddit/.*)'
